### ISSUE TITLE
2.2.2 Para. 4

### ISSUE THREAD

**Issue by spockcodes** [DS-USAFA/Probability-and-Statistics-for-Scientists-and-Engineers#1]
In para. 4 of this section the text describes `state` as a categorical variable of two-letter abbreviations for state names however, the dataset has state names stored a character  strings of complete state names.  Should we rewrite this text or update a local version of the dataset with two-letter abbreviations and have students use that one?

**Comment by DS-USAFA** [comment]
Either way would work. I have no preference. I think the original dataset had the two letter.
